import { checkNumber } from "./tasks/task1.js";
import { getSeason } from "./tasks/task2.js";
import { cutString1, cutString2, cutString3 } from "./tasks/task3.js";
import { changeString1, changeString2, changeString3 } from "./tasks/task4.js";
import { verify } from "./tasks/task5.js";
import { getDay } from "./tasks/task6.js";
import { getStr } from "./tasks/task7.js";
import { getRandom } from "./tasks/task8.js";
import { getArray } from "./tasks/task9.js";
import { getArray2 } from "./tasks/task10.js";
import { getElement } from "./tasks/task11.js";
import { getArray3 } from "./tasks/task12.js";
import { getArray4 } from "./tasks/task13.js";
import { getArray5 } from "./tasks/task14.js";
import { arrayFill } from "./tasks/task15.js";
import { calculate, arr } from "./tasks/task16.js";
import { getArr } from "./tasks/task17.js";
import { getArray6 } from "./tasks/task19.js";
import { getSum } from "./tasks/task20.js";
import { getDigitsSum } from "./tasks/task21.js";
import { getArr2 } from "./tasks/task22.js";


// console.log(checkNumber());
// console.log(getSeason());
// console.log(cutString1());
// console.log(cutString2());
// console.log(cutString3());
// console.log(changeString1());
// console.log(changeString2());
// console.log(changeString3());
// console.log(verify());
// console.log(getDay());
// console.log(getStr());
// console.log(getRandom());
// console.log(getArray());
// console.log(getArray2());
// console.log(getElement());
// console.log(getArray3());
// console.log(getArray4());
// console.log(getArray5());
// console.log(arrayFill('x', 5));
// console.log(calculate(arr));
// console.log(getArr());
// console.log(getArray6());
// console.log(getSum());
// console.log(getDigitsSum(52));
// console.log(getArr2());